[package]
name = "client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "window_message_probe"
path = "bin/window_message_probe.rs"

[dependencies]
num        = "0.4.3"
serde_json = "1.0.151"
rquickjs   = { version = "0.12.2",  features = ["full-async"] }
serde      = { version = "1.0.229", features = ["derive"] }
tokio      = { version = "1.53.1",  features = ["full"] }
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
