using System.Text.Json;

namespace RevIdle.ScoreTelemetry;

internal sealed record StateReq(IReadOnlyList<string> Keys) : IRequest<StateRes>;
internal sealed record StateRes(JsonElement Value);
internal sealed record UiPathReq(int X, int Y, int Width, int Height) : IRequest<UiPathRes>;
internal sealed record UiPathRes(string? Type, string? Path);
internal sealed record InvokeReq(string Path) : IRequest<InvokeRes>;
internal sealed record InvokeRes;
internal sealed record ScrollIntoViewReq(string Path) : IRequest<ScrollIntoViewRes>;
internal sealed record ScrollIntoViewRes;
internal sealed record TransferReq(string Source, string Destination) : IRequest<TransferRes>;
internal sealed record TransferRes;
internal sealed record SlotReq(string Path) : IRequest<SlotRes>;
internal sealed record SlotRes(JsonElement Value);
internal sealed record ClickCommand(int X, int Y, int Width, int Height);
internal sealed record ScrollCommand(int X, int Y, int Length, uint Axis, int Width, int Height);
internal sealed record DragCommand(int StartX, int StartY, int EndX, int EndY, int Width, int Height);
internal sealed record PressCommand(string Key);
internal sealed record ReloadScript;
internal sealed record ReloadLockedScript;
internal sealed record StopScript;
internal sealed record PauseScript;
internal sealed record ResumeScript;
internal sealed record ResumeLockedScript;
internal sealed record StartCapture;
internal sealed record StopCapture;
internal sealed record LockScript;
internal sealed record LoadScript(string Path, bool Locked);
internal sealed record RemoveScriptHistory(string Path);
internal sealed record StateUpdate(string Phase, bool Capture, bool Locked = false, IReadOnlyList<string>? Scripts = null);
